### ISSUE TITLE
Stage size controls

### ISSUE THREAD

**Issue by ericrosenbaum** [ericrosenbaum/BeetleBlocks#100]
We would like to have a set of four buttons that let you choose one of four stage sizes:

* mini
* standard [default]
* large
* full-screen

the mini and standard modes behave as they do now. the large stage size is 125% of standard. 

Ideally, full-screen mode would be a true full-screen. 

Here's a sketch of how the buttons could look:

![img_0304](https://cloud.githubusercontent.com/assets/567844/6654592/41e3175a-caa4-11e4-9981-e4d47d15433d.JPG)

**Comment by bromagosa** [comment]
Mistook this one for #103!

**Comment by bromagosa** [comment]
See:
![image](https://cloud.githubusercontent.com/assets/1016697/7176453/de470aa0-e41e-11e4-83ce-e6b6b915398c.png)
