### ISSUE TITLE
Change block size using scratch-like zoom controls

### ISSUE THREAD

**Issue by ericrosenbaum** [ericrosenbaum/BeetleBlocks#103]
We'd like to replace the current dialog for setting the size of the blocks with a set of three buttons in the bottom right corner of the scripting area, similar to the ones in Scratch. These are -, =, and + buttons (the = restores a default setting).

**Comment by bromagosa** [comment]
fixed in ff07b7bb7051e5a3ead6b8b330c1011b6c2d4a7d

**Comment by jmoenig** [comment]
nice! Once these GUI features are settled I'd love to evaluate which ones to merge back to Snap's main trunk! I bet Dan would love this one for his lectures...

**Comment by bromagosa** [comment]
Sure! Just let me know and I'll issue a pull request to Snap's main trunk :)
