### ISSUE TITLE
buttons and user interface

### ISSUE THREAD

**Issue by gitduks** [ericrosenbaum/BeetleBlocks#106]
I have been meaning to upload this in a while:

- We could have two buttons for camera related controls.
- Six check boxes to turn things on and off.
- The x,y,z coordinates separated.
- I added the three window presets (we could keep the shift-click version of the mini)
- I think the one pixel border of the individual frames could be white in all cases
- I added scratch-like zoom buttons for the scripting area
- The camera button could go away (and the remaining items could go into the gear)

![bb-ui](https://cloud.githubusercontent.com/assets/9574272/6817825/ad0cefd0-d27c-11e4-80cb-f181363bde59.jpg)

**Comment by gitduks** [comment]
Here is an updated version of UI changes:
- the camera and cloud icons are gone
- all grey backgrounds are the same (I think that should include the one behind the categories)
- the maximize 3d window icon is on the left in order to get the sequence right

![ui - ver0 2](https://cloud.githubusercontent.com/assets/9574272/6933758/ee9a5e7e-d7f9-11e4-8929-6445050f4fa7.jpg)

**Comment by bromagosa** [comment]
Nice!

All options under _Cloud_ and _Camera_ should go somewhere else, though. I'm guessing bg color and grid options should go under the _Config_ menu, and all cloud stuff under _File_, is that right?

**Comment by bromagosa** [comment]
Add **x: y: z:** to rotations too.

**Comment by gitduks** [comment]
Here are a few new suggestions:
- thinner lines for the enlarge stage to full screen button (these could also be an outline of the current version)
- add a triangle to the menu buttons on the left in order to distinguish them from regular buttons.
- add a white line between category selector and blocks panel.

![new ui 4-13](https://cloud.githubusercontent.com/assets/9574272/7129740/4585fea4-e232-11e4-91af-8a6137b97b18.jpg)

**Comment by bromagosa** [comment]
I'm slowly getting there...
