### ISSUE TITLE
Make background color consistent with scripring area and turn on grid as default

### ISSUE THREAD

**Issue by gitduks** [ericrosenbaum/BeetleBlocks#114]
I just tried that and the interface looks much better that way, imho. It would be great if the red, green and blue of the coordinate system was visible. I don't know if that means re-drawing the extensions of the x and y axes in grey.

**Comment by bromagosa** [comment]
Which color should i be?

**Comment by bromagosa** [comment]
*it (sorry, I'm replying from a mobile)

**Comment by bromagosa** [comment]
Done, I'm opening a new issue for the axes being sometimes hidden behind the grid...
