### ISSUE TITLE
Color scheme and Blocks Category Selector

### ISSUE THREAD

**Issue by gitduks** [ericrosenbaum/BeetleBlocks#122]
We have looked at a color scheme again and Eric pushed this version. Bernat, please let us know if you want the regular color scheme for your workshop!

Here is some of the rationale behind this darker color scheme:
Orange tones remain for variables and lists.
Green tones remain for operators.
Blue tones apply to motion, shapes and 'my Blocks'
Dark grey is used for control.
Zebra does not invert text to black.

I would like to use this in my seminar to get feedback form my students about this. It would be great to change the text color of the selected category in the Blocks Category Selector

**Comment by bromagosa** [comment]
There is an issue with the current color scheme when you embed control blocks inside a launch block:

![image](https://cloud.githubusercontent.com/assets/1016697/8079568/b61f8ef4-0f65-11e5-9dbe-6020b1af98b5.png)

**Comment by gitduks** [comment]
I guess we need to look at all blocks that are grey. I think we could make the default grey color a little lighter.
