### ISSUE TITLE
use absolute value of scale for geometry

### ISSUE THREAD

**Issue by ericrosenbaum** [ericrosenbaum/BeetleBlocks#124]
It's not clear exactly what a negative value for scale should do to geometry. If you set scale to -1 for example, "move 1" moves you by -1, which makes sense. But if you create a cube, it is inside out. I think we should never produce inside out geometry, since it renders incorrectly and probably causes other problems. arguably this is a bug.

So one simple fix would be to always take the absolute value of the scale when applying it to new geometry.

**Comment by bromagosa** [comment]
overriden by #91
