### ISSUE TITLE
embed code for thumbnail image link

### ISSUE THREAD

**Issue by ericrosenbaum** [ericrosenbaum/BeetleBlocks#145]
the one-click share system also gives you an embed code that displays the project thumbnail that links to the shared project

**Comment by bromagosa** [comment]
@jmoenig any news on the API call to retrieve a project's thumbnail?

**Comment by jmoenig** [comment]
working on it!

(also working on opening the Snap Cloud for other applications, such as Snapi)

-Jens

P.S. Great news about hardcoding codifications into Snap4Arduino today!

**Comment by bromagosa** [comment]
Oh wow! I can't tell you how happy people in my team will be to hear that! Thank you!

**Comment by bromagosa** [comment]
I think all these should be moved to the separate sharing site project. For now, https://github.com/bromagosa/beetlecloud could do.

**Comment by cycomachead** [comment]
@bromagosa You might find this useful: https://github-issue-mover.appspot.com

It closes the original issue and tags it, so everything is still linked.

**Comment by bromagosa** [comment]
Yep, thanks! I recently used it to move all Snap4Arduino issues into a new repo.

In this case, I guess I'll just start anew :)
