### ISSUE TITLE
tutorial pane

### ISSUE THREAD

**Issue by ericrosenbaum** [ericrosenbaum/BeetleBlocks#147]
We need something inside of beetleblocks to introduce new users to its functionality and guide them through some simple examples. I like the model used by Scratch 2.0, which shows a simple step-by-step tutorial inside a little pane the appears within the scripting area. It has a sequence of pages, with lots of animated gifs: 

![screen shot 2015-05-29 at 12 13 46 am](https://cloud.githubusercontent.com/assets/567844/7876305/b38faff2-0597-11e5-8d55-13c27bbfe2e1.jpg)

I've begun drafting the text for these tutorials here:
https://docs.google.com/document/d/1M14XZqhr7gJOagaYyK445-DTSq2F_8nK9LDyKoNCzQ8/edit?usp=sharing

How would we implement this? It needs to display a set of pages, with text, images, animated gifs, links forward and backward, and a menu. Can we display HTML pages within the editor? 

There's also the question of where the pane goes. Maybe we could use the lower part of the scripting area, and it when closed it could fold down to a little bar at the bottom. It would open by default in many cases (e.g. not signed in, new user, open to blank project).

**Comment by bromagosa** [comment]
See http://snapi.citilab.eu/#tutorial for my take on a Snap! tutorial. I just need a set of texts and PNGs to build a tutorial lite that for BeetleBlocks!

Oh well, that and some free time... :(

**Comment by nemilya** [comment]
http://snapi.citilab.eu/#tutorial is great! Is it github'ed?

**Comment by bromagosa** [comment]
@nemilya of course! The project is here: https://github.com/bromagosa/Snapi/
and the tutorial part is here: https://github.com/bromagosa/Snapi/blob/master/snapi/tutorial.js

Notice I've hardcoded the images in there, it doesn't have to be like this, I just needed to have this working ASAP and copy-pasted the base64 string straight away.

**Comment by bromagosa** [comment]
Forgot to say, it only works in flat design mode!

**Comment by bromagosa** [comment]
The tutorial should show up whenever BeetleBlocks detects it's never been opened in this browser before.

**Comment by bromagosa** [comment]
What about animated GIFs?
