### ISSUE TITLE
add 2D labels for axes

### ISSUE THREAD

**Issue by bromagosa** [ericrosenbaum/BeetleBlocks#148]
They should always face the camera and they should always be the same size (or close enough).

**Comment by awaywiththespoons** [comment]
Was just about to write this as an issue -I'm having a play now, and had to stop to work out the axis. I would say label all the axis, not just the 2D. If you are making a program aimed at kids, having all axis labeled would just skip a barrier.

**Comment by bromagosa** [comment]
What's 2D is the labels, not the axes ;)
