### ISSUE TITLE
Easier Interface

### ISSUE THREAD

**Issue by lilchap** [ericrosenbaum/BeetleBlocks#149]
Hello, I am recommending you add an easier interface to the website. I got pretty confused on the homepage and on the editor. You should add a hierarchy to the editor to sort things out, like objects.
Perhaps a community on the webpage also, like scratch to share projects easily with other people.

**Comment by bromagosa** [comment]
We're currently working on a tutorial, and constantly improving the UI and the site to make them easier for everyone :)

Thanks for your feedback!
