### ISSUE TITLE
Grid issues

### ISSUE THREAD

**Issue by awaywiththespoons** [ericrosenbaum/BeetleBlocks#150]
(working in firefox) 

When clicking inside the printing bed screen there is a problem with the grid -it redraws with every click until the whole screen is just "grid". I tried this in all the view modes and same thing happened.

![screen shot 2015-06-10 at 12 16 24 pm](https://cloud.githubusercontent.com/assets/5996068/8091736/8e53818c-0f6a-11e5-9ace-a71f0e0e0a6c.png)

**Comment by bromagosa** [comment]
Wow! How did that happen? O_O

Can you point me to the steps you followed? I can't reproduce that in any of my computers or browsers...

**Comment by awaywiththespoons** [comment]
hmmm. just had another go and it's not on click, it's mouse dragged that makes the grid go awol!

**Comment by gitduks** [comment]
We have been encouraging the use of Chrome as we have not really tested any other browsers yet...

**Comment by awaywiththespoons** [comment]
ahhh. I see. Just tested and it works fine in Chrome! 

I couldn't get anything to work at all in Firefox, maybe it would be worth noting that it should be used on Chrome in your warning in the try it now section?

**Comment by bromagosa** [comment]
But wait, I actually use Firefox and Chrome alternatively all the time, and never had an issue... what OS, Firefox version, etc are you using?

**Comment by awaywiththespoons** [comment]
oh that could be it. I'm not on yosemite. Firefox was updated a few days ago not sure of the verison.

**Comment by bromagosa** [comment]
@awaywiththespoons is this still happening? We never managed to reproduce this bug...

**Comment by bromagosa** [comment]
Since there's been no answer from @awaywiththespoons and nobody else complained about this, I'm closing this issue.
