### ISSUE TITLE
extrude → move → rotate x → move → weird twisting

### ISSUE THREAD

**Issue by bromagosa** [ericrosenbaum/BeetleBlocks#158]

**Comment by ericrosenbaum** [comment]
It's not just x axis rotation that causes the twisting at the extrusion joints- it can also be a combination of y and z rotations.

**Comment by bromagosa** [comment]
Is this still happening? I feel the fix I pushed today for extrusions should also take care of this...

**Comment by ericrosenbaum** [comment]
Yup, this is still a problem:

![screen shot 2015-07-20 at 12 34 06 am](https://cloud.githubusercontent.com/assets/567844/8769984/2593d5f8-2e77-11e5-8e20-a99e25cc5f79.jpg)

**Comment by bromagosa** [comment]
Check this one out, I think I may have mistaken an axis for another or something...

http://beetleblocks.com/run/#present:Username=ericrosenbizzle&ProjectName=code%20as%20form%20examples

**Comment by bromagosa** [comment]
@gitduks had an idea. We can use the intersection between both circles as a start point, and then move (counter?)clockwise from there and stitch the corresponding points.

**Comment by bromagosa** [comment]
After spending 10+ hours trying to fix the circle stitching issue (not kidding, I even dreamt about vertices tonight) I decided to look for alternative solutions and found out the latest three.js allows you to define the tension coefficient for Catmull-Rom curves.

What that means is we can achieve a pretty similar result for sharp edges with about 1/5th of the code, while smooth edges work much better now.

I've only found one example that wouldn't work well, all the rest look quite good.

![gas](https://cloud.githubusercontent.com/assets/1016697/10017160/6b2f0424-612c-11e5-933a-710645497c09.png)

I've adjusted it so the amount of segments is proportional to the length of the extrusion, so corners will look the same regardless of how long the path is:

![gas](https://cloud.githubusercontent.com/assets/1016697/10017182/9385ed34-612c-11e5-820a-9d5975c7e706.png)

An hexagon:
![image](https://cloud.githubusercontent.com/assets/1016697/10017211/c633fd8e-612c-11e5-8532-eb5ad66d1be3.png)

And our classical, smoother-looking examples:
![image](https://cloud.githubusercontent.com/assets/1016697/10017217/d8c4bd6c-612c-11e5-91c8-ca775a45dbcd.png)
![image](https://cloud.githubusercontent.com/assets/1016697/10017220/ddbd0a40-612c-11e5-9729-92faab8ee27c.png)
![image](https://cloud.githubusercontent.com/assets/1016697/10017221/e1638ab6-612c-11e5-9c15-128885f2da0c.png)

It's not all a bed of roses though, the snail example is broken, but I can redo it to have it be a little bit less extrusion-abusing.

I believe this is the best extrusion we've had so far, and is a good compromise between sharp and smooth angles...

**Comment by bromagosa** [comment]
Just a tiny change is required for the snail to look good again:
![image](https://cloud.githubusercontent.com/assets/1016697/10017660/ac72b53a-6130-11e5-9d50-2a866fb0aa83.png)

**Comment by ericrosenbaum** [comment]
this is amazing! thanks for all your hard work on this. 

what exactly did you have to change in the snail example? is this something users will have to know in general to avoid a problem, or is it something we can prevent?

**Comment by bromagosa** [comment]
Actually, I think I found the source of the problem!

**Comment by gitduks** [comment]
Is there a way to make sure 90 degree turns are consistent? We should fix the upper right corner in this example, no? It also looks like the inside corner renders correctly at the bottom left and upper right, but not for the other corners.

![new extrude-1](https://cloud.githubusercontent.com/assets/9574272/10034845/6493928e-6162-11e5-9be1-6fd0a2271730.jpg)

**Comment by bromagosa** [comment]
There should be a way, I guess. I need to investigate further.

For the sake of my sanity, I'll close this issue and open a new one about this particular problem.
