### ISSUE TITLE
comments in script pic

### ISSUE THREAD

**Issue by gitduks** [ericrosenbaum/BeetleBlocks#159]
It would be cool if the comments could be included in the script pic.

**Comment by bromagosa** [comment]
![image](https://cloud.githubusercontent.com/assets/1016697/9756104/cd62430e-56d7-11e5-8b96-cfeee39f9f01.png)

You need to right click on the scripting canvas and select "scripts pic...".

Thing is, this exports _all_ scripts in the canvas, including comments. If you want to export a single script with its comments, you should remove all other scripts from the canvas before. I don't think there is a better way at the moment, but maybe @jmoenig will prove me wrong :)

**Comment by bromagosa** [comment]
This was recently fixed in Snap!, so we got it fixed for free when merging.
