### ISSUE TITLE
Viewport resizing buttons

### ISSUE THREAD

**Issue by ShuraChechel** [ericrosenbaum/BeetleBlocks#161]
1) We would like to change the sequence of the viewprot resizing buttons:

![sequence](https://cloud.githubusercontent.com/assets/13890299/9391045/c0ce27f6-4742-11e5-8286-d09d3b2ade4c.jpg)

2) We would also like to redesign the buttons to make the new viewport rectangle more legible:

![redesign](https://cloud.githubusercontent.com/assets/13890299/9391516/28cec7b4-4745-11e5-93fe-1a2c7c9dc5c0.jpg)

**Comment by bromagosa** [comment]
Superseeded by #200
