### ISSUE TITLE
prevent slow-down and lock-up 

### ISSUE THREAD

**Issue by ericrosenbaum** [ericrosenbaum/BeetleBlocks#164]
When rendering complex projects, the UI sometimes responds slowly, or locks up completely for as long as 30 seconds. @bromagosa thought this might be prevented by slowing down the snap UI rendering loop.

**Comment by bromagosa** [comment]
Looks much better now, can you please confirm?

**Comment by ericrosenbaum** [comment]
so far so good. awesome! lets leave this open for a little while so we can keep testing.

**Comment by bromagosa** [comment]
Let's close this for now, recent performance improvements should have fixed this issue.
