### ISSUE TITLE
Draw polylines, and export polylines in SVG

### ISSUE THREAD

**Issue by ericrosenbaum** [ericrosenbaum/BeetleBlocks#167]
In the SVG export, rather than include each line as an individual line segment, we should combine contiguous lines into polylines. The problem is that the export happens after the geometry is created, and lines are represented as individual segments, so we would need to work out how they are connected (which can be ambiguous, if the line crosses itself at a vertex). 

@bromagosa and I discussed this and came up with a couple of ideas: store references to the threejs drawing points in order as they are created, or store an index representing the drawing order inside the threejs scene graph. 

I think a much better approach would be to change how we create the lines in the first place! The threejs line object can contain a whole list of vertices. so instead of creating lines individually at each step, we just need to keep track of a single line as it is being drawn. I'd guess this results in better rendering speed as well.

**Comment by gitduks** [comment]
In the spirit of extending state indicators; we could rethink the range of things that can 'start' and 'end'. We could have ('start line', 'stop line'),  ('start polyline', 'stop polyline'),  ('start spline', 'stop spline'),  ('start extrusion', 'stop extrusion').
Don't know if you like this, but it might appear more consistent to users that way, maybe?
