### ISSUE TITLE
splines

### ISSUE THREAD

**Issue by gitduks** [ericrosenbaum/BeetleBlocks#173]
I would be cool to have splines as an option to draw with. The type of spline could be a cardinal curve, which means that every beetle move results in a new a point on the curve:
![cardinal spline](https://cloud.githubusercontent.com/assets/9574272/9828376/63ca63c4-58ba-11e5-9670-d4bc4f0e146e.png)

The 'start drawing' block could include a drop-down menu where one can choose between 'start (line)' or 'start (spline)'.

**Comment by bromagosa** [comment]
If we do this, it would probably make sense to have different extrusion methods as well.

**Comment by gitduks** [comment]
Please take a quick look into this. You are right; there are several things to consider: have them show up on the screen, svg export and extrusion type. If this is hard, we can focus on other things.

**Comment by gitduks** [comment]
Wow, that was fast!!! Have two questions for you. One is about the 'resolution' of the spline in terms of how it is rendered and the second is bout the orientation of the SVG:

Is there a way to set the preview of the spline to be smooth? Also, the spline is not going through the points the beetle is going to. If the 'resolution' is based on numbers, switching from odd to even (or inverse) might maybe work?

![spline in bb](https://cloud.githubusercontent.com/assets/9574272/9997716/c6d57fc8-605b-11e5-9a66-94a0f22cfb15.jpg)

In the exported SVG the spline has the right behavior (see below), but it would be cool if we could rotate the drawing and set the artboard or canvas dimensions to 'inches' and not 'points'.

![spline in illustrator](https://cloud.githubusercontent.com/assets/9574272/9997723/ca401894-605b-11e5-9c5d-891d146be482.jpg)

**Comment by bromagosa** [comment]
The first one is just a matter of adding more control points to the splines in three.js. I'm doing that right now.

I think the second one should be discussed, because exporting in inches by default doesn't make much sense for the rest of the World. We either export to something agnostic (like pixels) or add an export dialog letting you choose units.

**Comment by gitduks** [comment]
Yes, that is a good point! It would be very cool to have a choice between 'inches' and 'cm' in a dialog box for example. The rotation still applies to both cases though.

We also need to look at the location of the x=0 and y=0 of the canvas (see below). If you draw a square with lines, the canvas is exactly the size of the square and has the top left as its 0,0. In the case below the canvas is misaligned:

![spline with off canvas](https://cloud.githubusercontent.com/assets/9574272/10035874/45b03e5c-616d-11e5-90c0-2e2c03c6880d.jpg)


![spline with off canvas - 2](https://cloud.githubusercontent.com/assets/9574272/10035877/4c15a796-616d-11e5-8319-bfdade334c8e.jpg)

**Comment by gitduks** [comment]
We could use the same 0,0 in BB as the 0,0 for the svg file. So in the above example the canvas would have it's origin where the beetle started to draw.
