### ISSUE TITLE
Offine version

### ISSUE THREAD

**Issue by microspace** [ericrosenbaum/BeetleBlocks#180]
Hello. Great project! I'd love to see offline (downloadable) version of Beetle Blocks!

**Comment by bromagosa** [comment]
Hi @microspace!

You can actually download BeetleBlocks and use it locally. Just get it here: https://github.com/ericrosenbaum/BeetleBlocks/archive/gh-pages.zip

Then double-click on the ``index.html`` file and you're all set :)
