### ISSUE TITLE
Slider on BeetleBlocks website is cropped at the top

### ISSUE THREAD

**Issue by ShuraChechel** [ericrosenbaum/BeetleBlocks#182]
![untitled-1](https://cloud.githubusercontent.com/assets/13890299/10921523/15419b7e-8244-11e5-8f24-f9b77f50f9bd.jpg)

**Comment by ericrosenbaum** [comment]
@gitduks will make new images for the carousel at the new wider aspect ratio (~1140 x 150)

**Comment by bromagosa** [comment]
Closing issues that are solved or rendered invalid by the BeetleCloud.
