### ISSUE TITLE
Go To Block Should Break Before Axis Labels

### ISSUE THREAD

**Issue by maryfries** [ericrosenbaum/BeetleBlocks#185]
The "go to" block should be breaking so that the "y:" and the "z:" are in front of their associated input slots—not on the previous lines.

![image](https://cloud.githubusercontent.com/assets/6549787/11011449/07171226-84b6-11e5-9487-913a3170d43b.png)

**Comment by maryfries** [comment]
See also: https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/999

**Comment by jmoenig** [comment]
breaks within blocks are strictly automatic. Some languages don't prefix parameters in a keyword-like fashion, but instead suffix them. There is some internal support for user-defined breaks, which isn't yet exposed in the GUI. I'm thinking about it...

**Comment by bromagosa** [comment]
I'm closing this, as Snap! already implements user-defined breaks, as shown [here].(https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/999#issuecomment-158833594)
