### ISSUE TITLE
Input sliders should not show up in text boxes that are not block inputs

### ISSUE THREAD

**Issue by bromagosa** [ericrosenbaum/BeetleBlocks#191]

**Comment by jmoenig** [comment]
so, this is actually intentional, as a way to use Snap on touch devices

**Comment by bromagosa** [comment]
oh wait, but does it make it possible to write text in there?

**Comment by cycomachead** [comment]
> so, this is actually intentional, as a way to use Snap on touch devices

When the keyboard works, I don't know if it's necessary, but we could easily detect if someone is on a touchscreen and only show sliders then.

**Comment by bromagosa** [comment]
![gas](https://cloud.githubusercontent.com/assets/1016697/11563669/6bea0102-99d5-11e5-86e1-2c4980fd9e22.png)

Are we talking about the same thing? I don't understand how this affects writing text in touch devices.

**Comment by cycomachead** [comment]
I had thought the very old idea, was that even when you couldn't write text, you could at least write _numeric_ text. (Though I agree in general, the slider isn't necessary there.)
