### ISSUE TITLE
New main menu design

### ISSUE THREAD

**Issue by ShuraChechel** [ericrosenbaum/BeetleBlocks#192]
![1](https://cloud.githubusercontent.com/assets/13890299/11516862/1fb2d53e-9854-11e5-9b9d-992ce30575a6.jpg)

**Comment by bromagosa** [comment]
As a general UI rule, shouldn't we position items from left to right and top to bottom according to how important or frequently used they are?

I agree it's important to have people create an account and log in, but once they're logged in they'll never need to click on these items any more, so I'd vote for moving them to the bottom.

**Comment by gitduks** [comment]
The idea was to create new groups that clearly belong together. I am not sure what is better in this case. We could also try to combine the 'login' and 'create an account' into a single dialog box that accommodates both.
Btw, I did not mean to get rid of the project notes, they should be at the bottom.

**Comment by ShuraChechel** [comment]
Since we have the new Login as part of the main UI, we can put the login, create an account and start tutorial at the bottom.

![menu github](https://cloud.githubusercontent.com/assets/13890299/12129025/05ebce76-b3cf-11e5-9035-baa8ad8ead95.jpg)

**Comment by bromagosa** [comment]
I'm on it! What's happened with "Save and share"? Should I remove it?
