### ISSUE TITLE
New login dialog box

### ISSUE THREAD

**Issue by ShuraChechel** [ericrosenbaum/BeetleBlocks#193]
We should rename the dialog box, make sure the buttons are visible, and add the 'reset password' button. Above the scripting area we are adding the 'login' - 'log out' button and the file name moves to the right.

![2](https://cloud.githubusercontent.com/assets/13890299/11516925/8a0db606-9854-11e5-9be9-e1bb15a686b5.jpg)

**Comment by bromagosa** [comment]
Closing issues that are solved or rendered invalid by the BeetleCloud.
