### ISSUE TITLE
New 'save as' dialog box

### ISSUE THREAD

**Issue by ShuraChechel** [ericrosenbaum/BeetleBlocks#195]
We should call the thumbnail 'thumbnail' and eliminate the light grey area below. If we agree to highlighting shared projects, we could call it 'publish' and add that button. On the sharing site we could 'hide' unpublished projects or grey them out.
![4](https://cloud.githubusercontent.com/assets/13890299/11517043/1e789c20-9855-11e5-8c3f-bc9419fcb635.jpg)

**Comment by bromagosa** [comment]
Closing issues that are solved or rendered invalid by the BeetleCloud.
