### ISSUE TITLE
Color picker dialog box

### ISSUE THREAD

**Issue by ShuraChechel** [ericrosenbaum/BeetleBlocks#198]
We could use small dialog box that would give users sliders for all 4 attributes. This might however be a lot of work to implement.  

![color picker](https://cloud.githubusercontent.com/assets/13890299/12247861/ea3a0116-b883-11e5-9522-7c1911dab898.jpg)

If we only use a color picker for the "hue" then we could use a wheel similar to this.

![color picker1](https://cloud.githubusercontent.com/assets/13890299/12247865/f1ba4810-b883-11e5-8275-c758c5879393.jpg)

**Comment by bromagosa** [comment]
Let's maybe start with the second one, which is almost trivial to implement.

I would need the same image but a bit larger and with no background.

Thanks! :)
