### ISSUE TITLE
New viewport resizing buttons

### ISSUE THREAD

**Issue by ShuraChechel** [ericrosenbaum/BeetleBlocks#200]
![resizing buttons](https://cloud.githubusercontent.com/assets/13890299/12336944/410d62f0-bad5-11e5-9645-076e03f04df5.jpg)

![button 5](https://cloud.githubusercontent.com/assets/13890299/12336948/4539433a-bad5-11e5-8f7c-2bbb35ee8ef2.jpg)
![button4](https://cloud.githubusercontent.com/assets/13890299/12336951/453d9ff2-bad5-11e5-809b-92c5400567c8.jpg)
![button 3](https://cloud.githubusercontent.com/assets/13890299/12336950/453c6e2a-bad5-11e5-9e48-d82dd719fc65.jpg)
![button 2](https://cloud.githubusercontent.com/assets/13890299/12336949/453c2226-bad5-11e5-843f-8a37f2e4a8a6.jpg)
![button 1](https://cloud.githubusercontent.com/assets/13890299/12336952/453f6f4e-bad5-11e5-8cf5-45b7ca830904.jpg)

**Comment by bromagosa** [comment]
Incorporate Snap!'s stage resize handle instead.
