### ISSUE TITLE
Zebra coloring bug

### ISSUE THREAD

**Issue by bromagosa** [ericrosenbaum/BeetleBlocks#205]
It seems a bug was introduced sometime in recent commits, as I don't recall this happening before:

![image](https://cloud.githubusercontent.com/assets/1016697/12670487/2baeeb32-c669-11e5-9736-8476b500ce3d.png)

If you take the embedded block out and put it back in, it shows up as it should:

![image](https://cloud.githubusercontent.com/assets/1016697/12670498/44c4e07c-c669-11e5-943c-f9c9671074d5.png)

**Comment by jmoenig** [comment]
not sure whether you have the latest round of little bug fixes from Snap. I've recently introduced a bunch of zebra-coloring bugs in optimizations which you might have pulled, and then I've fixed them again :-)
Sorry!

**Comment by bromagosa** [comment]
Oh I see, I'm pulling the latest changes then. Thanks, this was an easy one! :)

**Comment by bromagosa** [comment]
Hmm I did pull the latest changes and it's still there. I guess I proxied the function that fixes it... I'll take a look later!
