### ISSUE TITLE
clicked download button issue

### ISSUE THREAD

**Issue by killercatfish** [ericrosenbaum/BeetleBlocks#213]
A student clicked the download button without choosing an option.  The browser page started turning grey and needed to be refreshed!  She hadnt hit save, her fault, so lost some progress unfortunately!

**Comment by bromagosa** [comment]
Nice catch! I'm taking a look at this, thank you!

And sorry your student lost her project because of this bug... :(

**Comment by killercatfish** [comment]
Thanks!  No worries.  They need to learn to save!
