### ISSUE TITLE
User registration issues

### ISSUE THREAD

**Issue by aytac** [ericrosenbaum/BeetleBlocks#223]
Hi there,

There is a problem with the registration process on the site.
http://beetleblocks.com/api/users with this url we can see all registered user at the moment.
When you basically click http://beetleblocks.com/signup blank registration form you can see the users via site api.

Also when you submit the fully filled form it gives us an another error as well.
http://beetleblocks.com/api/users/new

**Comment by ericrosenbaum** [comment]
Thanks for this report. I'm going to move it over to the beetlecloud repository.
