### ISSUE TITLE
Can't open libraries

### ISSUE THREAD

**Issue by comeoneileen** [ericrosenbaum/BeetleBlocks#224]
Any attempt to open a library returns "Error: unable to retrieve libraries.[name].xml.xml". Wondering if that didn't migrate correctly to beta?

**Comment by bromagosa** [comment]
Thanks for reporting! I'll take a look today!

**Comment by bromagosa** [comment]
Fixed in 909bde9. We still should take a look at the libraries. Some of them don't make sense in Beetle Blocks, and we should add new ones for shapes and beetle movement too...
