### ISSUE TITLE
Won't Save

### ISSUE THREAD

**Issue by bwmartin44** [ericrosenbaum/BeetleBlocks#231]
I have a group of students using a shared account.  They are trying to save their projects, but when they save to the cloud, none of them are showing up on the My Projects page.

**Comment by bwmartin44** [comment]
On a different account I can access old saved files but nothing new will save.

**Comment by bromagosa** [comment]
Sorry, I was travelling. Is this still an issue?

If so, can you let me know the account name? I'll see what I can find out.

**Comment by bwmartin44** [comment]
vmsfablab

thanks for looking into it

**Comment by bromagosa** [comment]
Hi @bwmartin44, and sorry about the delay. I've been in a conference and then on a short vacation.

I've now fixed the issue. Thank you very much for reporting it and please excuse the trouble!
