### ISSUE TITLE
Project from 2017 now has 'obsolete' blocks

### ISSUE THREAD

**Issue by ToonTalk** [ericrosenbaum/BeetleBlocks#232]
http://beetleblocks.com/users/toontalk/projects/program%20interpolator

no longer works. 

![image](https://user-images.githubusercontent.com/2138696/43526510-51b8edb4-959c-11e8-9cfc-ca2f79ab443e.png)

While it used to look like this

![image](https://user-images.githubusercontent.com/2138696/43526551-6c405c26-959c-11e8-99bb-ea3d82fbe977.png)

A clue to what is going is that I can find the missing blocks

![image](https://user-images.githubusercontent.com/2138696/43526647-a5a28e94-959c-11e8-9979-c7e2d81f3f43.png)

But note that these are gray and I probably imported them from Snap!. These "missing" blocks I believe are still in the XML file.

The project stopped working some time this year.

**Comment by bromagosa** [comment]
Hi, Ken.

Can you please share the xml with us? I think I can make the project work for you...

**Comment by ToonTalk** [comment]
Hi. Thanks.

I needed to demonstrate this at Constructionism 2018 and found out that I had an old copy of BeetleBlocks that ran it fine - https://ecraft2learn.github.io/uui/beetleblocks/

The attached works fine in that version but has the same problem when imported from http://beetleblocks.com/run/# as well as a new problem:

Uncaught TypeError: Cannot read property 'drawImage' of null
    at Image.project.pentrails.onload (store.js:399)
[constructionism 2.zip]

(https://github.com/ericrosenbaum/BeetleBlocks/files/3836250/constructionism.2.zip)

**Comment by bromagosa** [comment]
Hi Ken,

the issue comes from the blocks in the "other" category, which doesn't exist in Beetle Blocks. I've manually moved them to "My blocks" and it now works okay.

Here's the fixed version: [constructionism 2.zip](https://github.com/ericrosenbaum/BeetleBlocks/files/3841172/constructionism.2.zip)

**Comment by ToonTalk** [comment]
Thanks - unshared the broken version and shared the working one.
