### ISSUE TITLE
Beetle stage doesn't show in Safari on MPB Retina

### ISSUE THREAD

**Issue by jmoenig** [ericrosenbaum/BeetleBlocks#41]
the stage just stays empty, no error message in the JS console. Strange. I'm investigating...

**Comment by bromagosa** [comment]
@jmoenig can you confirm whether this is still happening? If so, would merging your latest Snap! changes for retina displays fix this?

**Comment by jmoenig** [comment]
The stage now works fine on my MBP with retina display! What doesn't work is full-screen mode, but that's apparently an issue in Chrome, too. Merging the retina changes from Snap shouldn't affect the *visibility* of the stage, just its resolution, which frankly might cause other issues, although we should be able to mitigate them, the underlying mechanism devised by @bl-nero is nicely self-contained and straightforward.

**Comment by bromagosa** [comment]
Yeah, the full screen issue is cross-browser and entirely my fault. The social site and backend are taking all my time now, so I'm afraid it'll be a little while until I can fix it...

Happy to know the rest works though, I'll be closing this issue :)

Thanks!
