### ISSUE TITLE
URL?

### ISSUE THREAD

**Issue by ericrosenbaum** [ericrosenbaum/BeetleBlocks#42]
We need to figure out what the eventual URL for the beetleblocks project and editor will be. I own beetleblocks.com, which for now we can redirect to the github.io page. eventually, we will want to move the code over to be hosted at beetleblocks.com. Does that make sense?

**Comment by ericrosenbaum** [comment]
I just tried a little experiment - the hosting service I'm using for beetleblocks.com (1and1.com) was set to redirect to our gh-page, but I switched it to a "frame redirect" that keeps the beetleblocks.com URL while displaying the gh-page. This works in every respect except for one thing- there is no way to see the URL of a shared project, so you can't use the sharing feature. :(

There must be a better way to have this live at beetleblocks.com without having to copy it over from github to another server... is there?

**Comment by bromagosa** [comment]
Yep, this is not the proper way to do it. There is a nice short tutorial on this: https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

I'm creating the CNAME file right away, then you can do the rest from within your domain control panel :)
