### ISSUE TITLE
Cloud storage and sharing?

### ISSUE THREAD

**Issue by ericrosenbaum** [ericrosenbaum/BeetleBlocks#43]
Can and should we use the existing cloud system for Snap? 

If we do use it, we may want to re-think the sharing system. Ideally, we could have a page that lets you view any shared project.

**Comment by bromagosa** [comment]
Should we close this one? @jmoenig has already fixed this :)

**Comment by gitduks** [comment]
I think so, yes. Any objections, Eric?
