### ISSUE TITLE
Beetle Shape

### ISSUE THREAD

**Issue by ericrosenbaum** [ericrosenbaum/BeetleBlocks#44]
Change the beetle from its current cone shape to a simple but charismatic 3D model of a beetle (an OBJ file). Duks is working on a 3D file.

**Comment by ericrosenbaum** [comment]
proposed beetle design made in beetleblocks:

http://ericrosenbaum.github.io/BeetleBlocks/beetleblocks.html#present:Username=ericrosenbizzle&ProjectName=beetle

**Comment by bromagosa** [comment]
It flies when ``z > 0`` now! :)
