### ISSUE TITLE
Fix extrusion caps

### ISSUE THREAD

**Issue by ericrosenbaum** [ericrosenbaum/BeetleBlocks#47]
The caps at the beginning and end of each extrusion should be:

* hemispheres - half, not full spheres

* aligned - vertices in the hemisphere should connect to vertices in the extrusion tube

**Comment by gitduks** [comment]
Hi Bernat,

I would like to try to find someone who can help us with the cap and extrusion problem. It would be great if we could describe the problem we have.

I was initially hoping for the following:

A sphere should have a polygon setting for the equator and one for the longitudinal. If we can set both of them to the same multiple of 4, we should obtain a flat top and bottom and 'flat' tangents every 90 degrees.
A cylinder should have similar attributes and we could use the same multiple.
If the sphere does not have attributes for 2 polygons, but only one, then we could maybe rotate the sphere before adding the cylinder.

It is only important for 'extrude' to be tight along one single move. If the next move starts with a cap again, that is ok as the mesh preparation software we use will handle that. We just need a clean 'primitive'.

Could you describe the problem a little?
Thank you!!

**Comment by bromagosa** [comment]
http://stackoverflow.com/questions/12425014/create-a-concave-half-sphere-with-three-js

**Comment by gitduks** [comment]
Looked at this again. The cylinder is made of 8 quadrilaterals and the sphere has the corresponding section of 12 edges. The pole of the sphere is already in the right position and I think has the right resolution. I made these images to show the misalignment in a better way.
Can you specify the number of faces for a cylinder in 3js? If yes, we just have to increase the number of facets to 12




![extrude-combo1](https://cloud.githubusercontent.com/assets/9574272/7121637/e04ef548-e1e3-11e4-84c1-6171e0c0020e.jpg)

**Comment by bromagosa** [comment]
I've been looking at this as well, and there are already working solutions in three.js it seems. Take a look at this example: http://threejs.org/examples/#webgl_geometry_extrude_splines

If you add radius segments, that's pretty much what we want!

**Comment by bromagosa** [comment]
Nope... not fixed. The new flat cap brought a new bug:

![gas](https://cloud.githubusercontent.com/assets/1016697/7165523/6864438c-e3a8-11e4-96b5-0d6891346875.png)

**Comment by bromagosa** [comment]
Fixed now, but I had to move the cap to the end and place the sphere at the beginning.

**Comment by bromagosa** [comment]
Sorry about the comment flood.

@gitduks the new flat cap makes some old projects look funny. Should I add a sphere at the end of the extrusion along with the flat cap so all old projects look the same as they did before the change?

Here's an example:

![image](https://cloud.githubusercontent.com/assets/1016697/7165969/2b9e6b5a-e3ab-11e4-9091-7d13ef47c160.png)

**Comment by bromagosa** [comment]
Both ends should be flat!

**Comment by gitduks** [comment]
Adding a sphere at the end is probably the easiest fix for now. We can look at the selection of the examples once we have a good collection.

**Comment by bromagosa** [comment]
Added a sphere at the end too. I'm finally closing this (yay!).

**Comment by gitduks** [comment]
Any chance we could only add half spheres. This would make the stl files lighter.
