### ISSUE TITLE
Export to OBJ

### ISSUE THREAD

**Issue by bromagosa** [ericrosenbaum/BeetleBlocks#62]

**Comment by gitduks** [comment]
Hi Bernat,
Did you find a way to create an obj? I imagine it is not trivial to get drawn lines.
-d

**Comment by bromagosa** [comment]
Hey Duks,

I don't understand what you mean with drawn lines, I guess we need to talk about this feature some more ;)

I found a way to get the OBJExporter of three.js to work and export all objects in the scene. However, we need to test this quite extensively. I haven't even added it to the IDE menu yet, I thought it better to wait until we had out the next meeting.

If you want to test it though, you just need to open the javascript console and type ``ide.downloadOBJ()``. This is not pushed to the the gh-pages branch yet though, so you'd have to test it locally.

**Comment by bromagosa** [comment]
I've done quite a lot of testing and it seems to work. I still don't understand what @gitduks meant with drawn lines, but AFAIK this is already working.

I've exposed this on the file menu and contextual scene menu so you can try it out too. Some shots for context:

### BeetleBlocks scene
![image](https://cloud.githubusercontent.com/assets/1016697/5975062/ed5969b8-a87b-11e4-84bd-30c1e3319b76.png)
### Imported OBJ in MeshLab
![gas](https://cloud.githubusercontent.com/assets/1016697/5975052/d6f3ec02-a87b-11e4-94aa-453da17a7481.png)

**Comment by gitduks** [comment]
Hi Bernat,
This is sooo cool! What I meant is that a line that was created with 'start drawing', ' stop drawing does not show up the obj.

![obj test in bb](https://cloud.githubusercontent.com/assets/9574272/5986484/4f69d8d6-a8c7-11e4-873b-27bd9021fde0.jpg)


![obj test in rhino3d](https://cloud.githubusercontent.com/assets/9574272/5986485/55d86fc0-a8c7-11e4-9f58-098279297945.jpg)

**Comment by bromagosa** [comment]
Ok, I understand now.

Then, since OBJ exporting does work, I'm closing this one and opening a new issue for missing lines when exporting.
