### ISSUE TITLE
block names and convention for dimensions

### ISSUE THREAD

**Issue by gitduks** [ericrosenbaum/BeetleBlocks#66]
This is still all in discussion...

relative coordinates in lower case:
[rotate z by (15)]

absolute coordinates in upper case:
[change X by (12)]

We have to make the following consistent:
- diameter vs radius
- x (red), y (green), z (blue)
- X (red), Y (green), Z (blue) (maybe bold instead?)
- length, width, height vs height and depth
- to vs. towards
- inside diameter - outside diameter, i.dia - o.dia.,  i.d. - o.d.

**Comment by gitduks** [comment]
Hi Bernat,
I wanted to ask you how much work it would be to revert the capitalized X,Y,Z back to lower case x,y,z. Eric and I had a long conversation and in almost all cases it is obvious which x we mean. The only block that is confusing is the <change x by> block as it affects an absolute change in x. All others are pretty clear and don't need disambiguation...
We could resolve that with changing the name of the block to <change absolute x by> and keep all coordinates lower case.
Possible?
If yes, then we could keep this open with:

All x,y,z labels are lower case.
rename <change x by> to <change absolute x by>

**Comment by bromagosa** [comment]
Sure, it's no problem, and I completely agree! I'll try to have it done by the end of this morning.

However, that'll force me to reconvert all projects back again, I may not have the time to do that today.

BTW I think you pressed comment before finishing your last sentence ;)

**Comment by bromagosa** [comment]
I've fixed all labels, and resaved all example projects so they follow the new (old?) standard.

Waiting for the new "go to" phrasing :)

**Comment by bromagosa** [comment]
@gitduks is there something else that needs renaming?

If not, we can close this.

**Comment by gitduks** [comment]
Hi Bernat,
Looks like you got all of them except for change by:
[change x by (1)] should be [change absolute x by (1)]
