### ISSUE TITLE
Rename blocks in 'Shapes' category

### ISSUE THREAD

**Issue by gitduks** [ericrosenbaum/BeetleBlocks#84]
The general convention is:
The length is L:
The width is W:
The height is H:
Size is now dimension and is abbreviated to Dim.
Diameter is Dia.

'cube size (0.5)' should be 'cube Dim. (0.5)'
'sphere diameter (0.5)' should be 'sphere Dia. (0.5)'
'text [hello] height(1) depth(0.5)' should be 'text [hello] H: (1) W:(0.5)'
'set extrusion diameter to (1)' should be 'set extrusion Dia.to (1)'
'change extrusion diameter by (1)' should be 'change extrusion Dia. by (1)'

**Comment by bromagosa** [comment]
Hey Ducks, I think something went wrong in all of your recent comments, here's what I see:

![gas](https://cloud.githubusercontent.com/assets/1016697/5774382/648b1dfc-9d6d-11e4-8449-5f175f7ef129.png)

**Comment by gitduks** [comment]
Sorry see above...
