### ISSUE TITLE
Allow exporting to a format that supports lines

### ISSUE THREAD

**Issue by bromagosa** [ericrosenbaum/BeetleBlocks#88]

**Comment by bromagosa** [comment]
The funny part is that vertices are exported, but lines in between these vertices do not show up:

![image](https://cloud.githubusercontent.com/assets/1016697/5998774/775c60d8-aacb-11e4-9eab-1f7556614703.png)

![gas](https://cloud.githubusercontent.com/assets/1016697/5998772/6c0c4c84-aacb-11e4-8c6e-dc4d3c717c02.png)

**Comment by bromagosa** [comment]
I'm reformulating this issue, as we've found out OBJ doesn't support things without volume.

**Comment by bromagosa** [comment]
@gitduks these are the formats we can easily export into:

https://github.com/mrdoob/three.js/tree/master/examples/js/exporters

Could you check whether SceneExporter or TypedGeometryExporter are what we need?

**Comment by gitduks** [comment]
I don't think these will work. Did someone look into any of these:
.dxf, .3ds, .3dm?
