### ISSUE TITLE
Single sprite

### ISSUE THREAD

**Issue by bromagosa** [ericrosenbaum/BeetleBlocks#9]
As @ericrosenbaum says:

> below the stage, we can remove the sprite library entirely.

IMO, the Stage blocks don't make much sense either. This is a single-object world (the beetle), and segregating some blocks into the Stage will only confuse users.

**Comment by comeoneileen** [comment]
Is the choice when creating a variable to make it "for this sprite only" vs. "for all sprites" just a vestige of multiple sprite days, then, or does that serve some purpose that's beyond me?

![screen shot 2016-02-21 at 1 06 55 pm](https://cloud.githubusercontent.com/assets/2829021/13204700/2d611104-d89c-11e5-9915-40b8c72de734.png)

**Comment by bromagosa** [comment]
Just a vestige of the old days, I'm removing it :)

Thanks for reporting this!
