### ISSUE TITLE
Trig errors? 

### ISSUE THREAD

**Issue by ericrosenbaum** [ericrosenbaum/BeetleBlocks#90]
This project demonstrates a very strange problem. Apparently combining a lot of 90 degree rotations can sometimes create large errors in the resulting angle... It seems to happen only if the rotations are aligned with the global axes. Maybe it's related to behavior of trig functions at 0 degrees? 

One stack in the project creates a cube fractal that shows the error (top cubes are tilted! see screenshot). Another stack with a tiny initial rotation (but otherwise identical) gives the expected behavior (cubes behaving themselves cubely). 

http://ericrosenbaum.github.io/BeetleBlocks/beetleblocks.html#present:Username=ericrosenbizzle&ProjectName=cube%20fractal

![screen shot 2015-02-10 at 7 33 52 pm](https://cloud.githubusercontent.com/assets/567844/6139656/07b2aa48-b15c-11e4-9196-b251b1553e66.jpg)

**Comment by bromagosa** [comment]
I got this exact bug a while ago, but I thought it was my script that was wrong!

I'll take a look as soon as I can.

**Comment by bromagosa** [comment]
Funnily, this works:
![image](https://cloud.githubusercontent.com/assets/1016697/6554965/7161011e-c661-11e4-9f74-356cbe473ca1.png)
but this doesn't:
![image](https://cloud.githubusercontent.com/assets/1016697/6554969/7a622c48-c661-11e4-91fe-b441dd7617a7.png)
Apparently, three.js is rounding numbers internally.

**Comment by bromagosa** [comment]
http://ericrosenbaum.github.io/BeetleBlocks/beetleblocks.html#present:Username=bromagosa&ProjectName=bug

So my project works in my home PC in Firefox, but not in Chrome.

Eric's project doesn't work anywhere in my home PC, but it does work at my work PC... :(

**Comment by bromagosa** [comment]
Yay! Fixed by updating to the latest three.js version!
