### ISSUE TITLE
Negative geometry

### ISSUE THREAD

**Issue by bromagosa** [ericrosenbaum/BeetleBlocks#91]
There has been a request for a mode where any shape created is negative, meaning it creates holes in whatever other geometry it intersects with.

Is there any interest in this?

**Comment by gitduks** [comment]
Am not sure about this. Eric and I should have a conversation about this I think. Generally I am in favor of adding features and functionality, but this might be complicated as we don't usually 'call' a geometric object. Having lists of geometric objects might be interesting, though...

**Comment by bromagosa** [comment]
I've got a __very__ early prototype kind of working, but the resulting geometries are ugly as hell!

Check this out, it's just a cube from which I subtracted a sphere, then I placed a smaller sphere in the same position as the negative one:

![image](https://cloud.githubusercontent.com/assets/1016697/6948021/56afd5b4-d8ab-11e4-9b9b-f1f41384c822.png)

Just look at the wireframe... it's a disaster:

![image](https://cloud.githubusercontent.com/assets/1016697/6948031/5ffd2f2c-d8ab-11e4-9665-78ab78c2d908.png)

This was achieved by using [this library](https://github.com/chandlerprall/ThreeCSG). I'll keep digging to see if there's something better out there...

**Comment by bromagosa** [comment]
Forget it, it may work!

![image](https://cloud.githubusercontent.com/assets/1016697/6948826/9110373a-d8b0-11e4-9d7c-ca690b703113.png)

**Comment by gitduks** [comment]
Very cool! If it works for cuboids and spheres we can already do a lot!!

**Comment by nemilya** [comment]
Thanks! Looks interesting

**Comment by ericrosenbaum** [comment]
how about 3 blocks:

subtract cube dim. []
subtract sphere diam. []
subtract cuboid l: [] w: [] h: []

**Comment by ericrosenbaum** [comment]
Lets clip scale at zero, so it can never go negative

Remove the negative geometry blocks from the palette

Detect when you make a cube, cuboid or sphere with a negative dimension, and switch to negative geometry mode

Then we can add a block in a library that wraps this functionality - basically invert the dimensions you give it

**Comment by bromagosa** [comment]
I'm closing this, as we do kind of have negative geometry already.

Let's open new issues for bugs and improvements to this.
