### ISSUE TITLE
Loading a project via #present disables buttons under the Stage

### ISSUE THREAD

**Issue by bromagosa** [ericrosenbaum/BeetleBlocks#92]

**Comment by gitduks** [comment]
It seems that the 4 switches don't work in older projects. This project also does not show the variables in the area under the 3d window.

http://ericrosenbaum.github.io/BeetleBlocks/beetleblocks.html#present:Username=descomp&ProjectName=2D%20Hatch%20Square

**Comment by bromagosa** [comment]
You mean this does work in newer projects?

**Comment by gitduks** [comment]
It happens often when we use shared files in class. Some of them I made right before the class started in January. If you start a new project it seems to be fine.
The variables not showing up seems to occur on new projects that have been played with a lot, too.

**Comment by bromagosa** [comment]
This one was hard to track! Since it was a problem only showing up when loading from the cloud, I couldn't test it in local...

Anyways, it's been fixed now in c84f9da0c11570131b99705b33494ad025eb8fde.
