### ISSUE TITLE
Combine browser and cloud saving

### ISSUE THREAD

**Issue by ericrosenbaum** [ericrosenbaum/BeetleBlocks#97]
I'd like to re-think the way in which the user's files are represented. I think having files stored both in the browser and in the cloud is potentially confusing.

One solution would be to simplify the file save/open system so that there is no choice between "browser" and "cloud" files. You just save a file, and it always gets saved in the cloud. 

We can simultaneously save the file in the local storage, but this would only be a way to accelerate loading the project in the case that you go to open again later and the server reports that there is not a newer version than the one you have.

This also means that in order to save a file at all, you need to be logged in. But that seems okay.

**Comment by bromagosa** [comment]
Superseeded by #195
