### ISSUE TITLE
One-click share

### ISSUE THREAD

**Issue by ericrosenbaum** [ericrosenbaum/BeetleBlocks#99]
Currently it is pretty complicated to share a project (it's about 10 clicks or so). I'd like to be able to share a project in one click.

If we collapse browser and cloud storage into one type of save, then you can assume that the project is always being saved in the cloud. 

We could have a button on the top bar (to the right of the project name, say) that lets you share with one click. If the file has already been saved at least once, clicking the "share" button saves the file and copies the link to the shared file into your clipboard. You would get a notification after this process completes (like how dropbox behaves when you create a link to a shared file). If the file has not been saved yet, clicking the share button takes you to the "save as" dialog, then once it's saved, it would automatically initiate the same sharing process, copy the link and notify you.

**Comment by bromagosa** [comment]
Good idea! But there is the same issue with accessing the clipboard... maybe we could pop up a dialog box with the URL advising you to copy it?
